### PR TITLE
Extra characters

### PR DESCRIPTION
**Pull request by Nothing00100**

### CODE REVIEW

**Comment by Iddmeister** [comment]
Can't do this right now, but will get to it at some point today (probably)

**Comment by Iddmeister** [comment]
Pie-per and 64-bit don't have supers, could we have some suggestions?

**Comment by Nothing00100** [comment]
@Iddmeister 64 bit: more damage per bullet, pie: really fast reload speed (like 5-10x), brick: invulnerability shield for some duration of time.

**Comment by Iddmeister** [comment]
@Nothing00100  Will do (at some point, probably)

**Comment by Nothing00100** [comment]
@Iddmeister ADD IT SOON OR I WILL KEEP HARASSING YOU!!

**Pull request closed without merging**
